WLA3/WLA3/Models/jurisdiction_price.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jurisdiction_price
    {
        public string client_id { get; set; }
        public int jurisdiction_price_id { get; set; }
        public Nullable<int> jurisdiction_id { get; set; }
        public string processing_type { get; set; }
        public string code { get; set; }
        public string price_or_percent { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_min { get; set; }
        public Nullable<decimal> price_max { get; set; }
        public Nullable<decimal> price_percent { get; set; }
        public Nullable<int> tag_term { get; set; }
        public Nullable<int> tag_term_avail { get; set; }
        public string juvenile_tag { get; set; }
        public string description { get; set; }
        public string disclaimer { get; set; }
        public string availability_renew { get; set; }
        public string availability_new { get; set; }
        public Nullable<int> date_interval { get; set; }
        public string per_trans_or_item { get; set; }
        public Nullable<System.DateTime> date_effective { get; set; }
        public Nullable<short> effective_delta_years { get; set; }
        public Nullable<System.DateTime> date_expires { get; set; }
        public Nullable<short> expires_delta_years { get; set; }
        public string display_jursidiction { get; set; }
        public string display_licenseselect { get; set; }
        public int sort_order { get; set; }
        public string location { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
    
        public virtual jurisdiction jurisdiction { get; set; }
    }
}

WLA3/WLA3/ViewModels/WLA_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WLA3.Models;

namespace WLA3.ViewModels
{
	public class WLA_ViewModel
	{ 
		public class WLAVM
		{
			public CustomModels.ClientLookupModel ClientLookupModel { get; set; }
			public List<CustomModels.IdentifierLookupList> CM_ILL { get; set; }
			public CustomModels.IdentifierVM IdentifierVM { get; set; }
			public ClientConfiguration ClientConfig { get; set; }
			public ValidConfiguration ValidConfig { get; set; }
			public JurisdictionConfiguration JConfig { get; set; }
			public List<JurisdictionPriceConfiguration> JPriceConfig { get; set; }

			public List<JurisdictionConfiguration> JInfo { get; set; }

			public List<LockboxConfiguration> LBInfo { get; set; }
			public LockboxConfiguration LBConfig { get; set; }
		}
	}
}

WLA3/WLA3/Controllers/WLAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WLA3.Models;
using WLA3.ViewModels;
using static WLA3.Models.CustomModels;


namespace WLA3.Controllers
{
	public class WLAController : Controller
	{

		DatabaseController dbC = new DatabaseController();

		public ActionResult Index() => View(new Master_ViewModel.MVM());


		/// <summary>
		/// Takes in the shelter code and SQL connection info to return all the jurisdictions for that shelter - First page after hitting 'WLA3' Selection in header
		/// </summary>
		/// <param name="wlavm"></param>
		/// <returns></returns>
		//[Route("GetIdentifierList")]
		[HttpGet]
		public ActionResult GetIdentifierList(/*ClientLookupModel clientInfo*/ /*WLA_ViewModel.WLAVM wlavm*/)
		{
			var master = new Master_ViewModel.MVM();
			master.WLAVMMaster = new WLA_ViewModel.WLAVM();
			master.WLAVMMaster.ClientLookupModel = new ClientLookupModel();
			master.WLAVMMaster.ClientLookupModel.User = Session["User"].ToString();
			master.WLAVMMaster.ClientLookupModel.Password = Session["Password"].ToString();
			master.WLAVMMaster.ClientLookupModel.ClientId = Session["ClientId"].ToString();

			if (master.WLAVMMaster.ClientLookupModel == null || (master.WLAVMMaster.ClientLookupModel.User == null || master.WLAVMMaster.ClientLookupModel.Password == null || master.WLAVMMaster.ClientLookupModel.ClientId == null))
			{
				if (master.WLAVMMaster == null)
					master.WLAVMMaster = new WLA_ViewModel.WLAVM();
				if (master.WLAVMMaster.ClientLookupModel == null)
					master.WLAVMMaster.ClientLookupModel = new ClientLookupModel();
				var unpw = dbC.GetUNPW();
				master.WLAVMMaster.ClientLookupModel.User = unpw.User;
				master.WLAVMMaster.ClientLookupModel.Password = unpw.Password;
				master.WLAVMMaster.ClientLookupModel.ClientId = unpw.ClientId;
			}

			dbC.SetUNPW("WA", master.WLAVMMaster.ClientLookupModel.User, master.WLAVMMaster.ClientLookupModel.Password, master.WLAVMMaster.ClientLookupModel.ClientId);
			//var master.WLAVMMaster = new WLA_ViewModel.WLAVM();
			master.WLAVMMaster.CM_ILL = new List<IdentifierLookupList>();
			master.WLAVMMaster.CM_ILL.Add(new IdentifierLookupList
			{
				JurisdictionId = 0,
				ClientId = master.WLAVMMaster.ClientLookupModel.ClientId.ToUpper(),
				JurisdictionName = "Default",
				JurisdictionZipcodes = "All"
			});

			var lists = dbC.getIdentifierList(master.WLAVMMaster);

			foreach (var item in lists)
			{
				item.JurisdictionZipcodes = item.JurisdictionZipcodes.Replace(",", ", ").Replace('.', ',').Replace(" ,  ", ", ");
				master.WLAVMMaster.CM_ILL.Add(item);
			}

			master.WLAVMMaster.JInfo = new List<JurisdictionConfiguration>();
			master.WLAVMMaster.JInfo = dbC.getJurisdictionInfo(master.WLAVMMaster.ClientLookupModel.ClientId);

			master.WLAVMMaster.LBInfo = new List<LockboxConfiguration>();
			master.WLAVMMaster.LBInfo = dbC.getLockboxValidations(master.WLAVMMaster.ClientLookupModel.ClientId.ToUpper());

			return View("ClientPreferences", master);
		}

		/// <summary>
		/// Allows the adding of template/non-template Jurisdiction and Price records
		/// </summary>
		/// <param name="identifierListParams"></param>
		/// <returns></returns>
		[HttpGet]
		public ActionResult AddJurisdiction(IdentifierListParams identifierListParams)
		{
			var master = new Master_ViewModel.MVM();
			master.WLAVMMaster = new WLA_ViewModel.WLAVM();
			master.WLAVMMaster.ClientLookupModel = new ClientLookupModel();
			master.WLAVMMaster.ClientLookupModel.ClientId = identifierListParams.ClientId;


			if (identifierListParams.ActionType == "Temp")
			{
				//find our template to fill out our new form
				var templateJurisdiction = dbC.GetTemplateJurisdiction(identifierListParams.ClientId, identifierListParams.JurisdictionId);
				master.WLAVMMaster.JConfig = templateJurisdiction;

				var templateJPriceRecords = dbC.GetJurisdictionPriceRecords(identifierListParams.ClientId, identifierListParams.JurisdictionId);
				///Add new template price records to get up to a max of 40 so we can add or remove records
				for (var i = templateJPriceRecords.Count; i < 40; i++)
				{
					templateJPriceRecords.Add(new JurisdictionPriceConfiguration()
					{
						InUse = false
					});
				}

				master.WLAVMMaster.JConfig.JurisdictionPrice = new List<JurisdictionPriceConfiguration>();
				master.WLAVMMaster.JConfig.JurisdictionPrice = templateJPriceRecords;
			}
			else
			{
				master.WLAVMMaster.JConfig = new JurisdictionConfiguration();
				master.WLAVMMaster.JConfig.ClientId = identifierListParams.ClientId;
				master.WLAVMMaster.JConfig.JurisdictionId = identifierListParams.JurisdictionId;

				master.WLAVMMaster.JConfig.JurisdictionPrice = new List<JurisdictionPriceConfiguration>();
				///Add new template price records to get up to a max of 40 so we can add or remove records
				for (var i = 0; i < 40; i++)
				{
					master.WLAVMMaster.JConfig.JurisdictionPrice.Add(new JurisdictionPriceConfiguration()
					{
						InUse = false
					});
				}
			}


			return View("AddJurisdiction", master);
		}

		/// <summary>
		/// Takes new Jurisdiction and Price information and adds them to the database
		/// </summary>
		/// <param name="wlavm"></param>
		/// <returns></returns>
		[HttpPost]
    [ValidateInput(false)]
    public ActionResult AddJurisdiction(Master_ViewModel.MVM master)
		{
			if (master.WLAVMMaster.JConfig != null)
			{
				var jurisdictionId = dbC.InsertJurisdiction(master.WLAVMMaster.JConfig);
				if (master.WLAVMMaster.JConfig.JurisdictionPrice != null)
				{
					foreach (var item in master.WLAVMMaster.JConfig.JurisdictionPrice)
					{
						if (item.InUse == true)
						{
							dbC.InsertJurisdictionPrice(item, jurisdictionId);
						}
					}
				}
			}

			return RedirectToAction("GetIdentifierList");
		}




		[HttpGet]
		public ActionResult EditJurisdictionPrice(int jurisdictionId)
		{
			var master = new Master_ViewModel.MVM();
			master.WLAVMMaster = new WLA_ViewModel.WLAVM();
			var clientId = Session["ClientId"].ToString();
			//master.WLAVMMaster.ClientLookupModel = new ClientLookupModel();
			//master.WLAVMMaster.ClientLookupModel.User = Session["User"].ToString();
			//master.WLAVMMaster.ClientLookupModel.Password = Session["Password"].ToString();
			//master.WLAVMMaster.ClientLookupModel.ClientId = Session["ClientId"].ToString();
			//// Get Jurisdiction records
			//// Display all records for that jurisdiction
			master.WLAVMMaster.JConfig = new JurisdictionConfiguration();
			master.WLAVMMaster.JConfig.ClientId = Session["ClientId"].ToString();
			master.WLAVMMaster.JConfig.JurisdictionId = jurisdictionId;

			var templateJurisdiction = dbC.GetTemplateJurisdiction(clientId, jurisdictionId);
			master.WLAVMMaster.JConfig = templateJurisdiction;

			var templateJPriceRecords = dbC.GetJurisdictionPriceRecords(clientId, jurisdictionId);
			///Add new template price records to get up to a max of 40 so we can add or remove records
			for (var i = templateJPriceRecords.Count; i < 40; i++)
			{
				templateJPriceRecords.Add(new JurisdictionPriceConfiguration()
				{
					ClientId = Session["ClientId"].ToString(),
					JurisdictionId = jurisdictionId,
					IsUpdate = false,
					InUse = false
				});
			}

			master.WLAVMMaster.JConfig.JurisdictionPrice = new List<JurisdictionPriceConfiguration>();
			master.WLAVMMaster.JConfig.JurisdictionPrice = templateJPriceRecords;


			return View("UpdateJurisdictionPrice", master);
		}

		[HttpPost]
    [ValidateInput(false)]
    public ActionResult EditJurisdictionPrice(Master_ViewModel.MVM master)
		{

			foreach (var item in master.WLAVMMaster.JConfig.JurisdictionPrice)
			{
				// Create
				if (item.InUse == true && item.JurisdictionPriceId == 0)
				{
					dbC.addNewJurisdictionPriceRecord(item);
				}
				// Update
				else if (item.InUse == true && item.JurisdictionPriceId != 0 && item.IsUpdate == true)
				{
					dbC.updateJurisdictionPriceRecord(item);
				}
				// Delete -> Item is not in use and the jPrice id is not 0
				else if (item.InUse == false && item.JurisdictionPriceId != 0)
				{
					dbC.deleteJurisdictionPriceRecord(item.JurisdictionPriceId);
				}
			}

			return RedirectToAction("GetIdentifierList");
		}


		[HttpPost]
    [ValidateInput(false)]
    public ActionResult UpdateJurisdictionInfo(Master_ViewModel.MVM master)
		{
			dbC.updateJuridictionInfo(master.WLAVMMaster.JConfig);

			var iList = new IdentifierListParams();
			iList.ClientId = master.WLAVMMaster.JConfig.ClientId;
			iList.JurisdictionId = master.WLAVMMaster.JConfig.JurisdictionId;

			if (master.WLAVMMaster.JConfig.OutOfArea == true)
			{
				return RedirectToAction("GetIdentifierList", master.WLAVMMaster.ClientLookupModel);
			}
			else
			{
				return RedirectToAction("EditIdentifierList", iList);
			}


		}

		/// <summary>
		/// Edit the params in an out of area jurisdiction
		/// </summary>
		/// <param name="identifierListParams"></param>
		/// <returns></returns>
		[HttpGet]
		public ActionResult EditOutOfAreaJurisdiction(IdentifierListParams identifierListParams)
		{
			var master = new Master_ViewModel.MVM();
			master.WLAVMMaster = new WLA_ViewModel.WLAVM();
			master.WLAVMMaster.JConfig = new JurisdictionConfiguration();

			/// When editing the Default, there will never be any jurisdiction price config so we can skip all of this
			if (identifierListParams.ClientId.ToUpper() != "DEFAULT" && identifierListParams.JurisdictionId != 0)
			{
				var updateJurisInfo = dbC.GetUpdateJurisdictionInformation(identifierListParams.ClientId, identifierListParams.JurisdictionId);

				master.WLAVMMaster.JConfig = updateJurisInfo;
			}
			master.WLAVMMaster.ClientLookupModel = new ClientLookupModel();
			master.WLAVMMaster.ClientLookupModel.ClientId = identifierListParams.ClientId;

			master.WLAVMMaster.JConfig.JurisdictionId = identifierListParams.JurisdictionId;

WLA3/WLA3/Views/WLA/AddJurisdiction.cshtml
@model WLA3.ViewModels.Master_ViewModel.MVM
@{
    ViewBag.Title = "Add Jurisdiction";
}

@Html.ActionLink("Home", "GetIdentifierList", "WLA")
<hr/>

<h2>Add Jurisdiction</h2>

<p>Client Id: @Model.WLAVMMaster.JConfig.ClientId</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.WLAVMMaster.JConfig.ClientId)
        @Html.HiddenFor(model => model.CLM.ClientId)
        @Html.HiddenFor(model => model.CLM.User)
        @Html.HiddenFor(model => model.CLM.Password)

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.Jurisdiction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WLAVMMaster.JConfig.Jurisdiction, new { htmlAttributes = new { @class = "form-control", @maxlength = "15" } })
                @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.Jurisdiction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.JurisdictionTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WLAVMMaster.JConfig.JurisdictionTitle, new { htmlAttributes = new { @class = "form-control", @maxlength = "50" } })
                @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.JurisdictionTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.JurisdictionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WLAVMMaster.JConfig.JurisdictionDescription, new { htmlAttributes = new { @class = "form-control", @maxlength = "1000" } })
                @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.JurisdictionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.Zipcodes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WLAVMMaster.JConfig.Zipcodes, new { htmlAttributes = new { @class = "form-control", @maxlength = "1000" } })
                @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.Zipcodes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.OutOfArea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.WLAVMMaster.JConfig.OutOfArea)
                    @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.OutOfArea, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WLAVMMaster.JConfig.OutOfAreaURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WLAVMMaster.JConfig.OutOfAreaURL, new { htmlAttributes = new { @class = "form-control", @maxlength = "1000" } })
                @Html.ValidationMessageFor(model => model.WLAVMMaster.JConfig.OutOfAreaURL, "", new { @class = "text-danger" })
            </div>
        </div>


        <hr />
        @{Html.RenderPartial("_JurisdictionPrice", Model);}


        <div class="clearfix"></div>
        <div class="form-group" style="margin-top: 10px;">
            <input type="submit" value="Save" class="btn btn-success" style="width: 75%; display: block; margin: 0 auto;" />

        </div>
    </div>
}


@section Scripts{

    <script type="text/javascript">
        var globalLastIndex = 0;

        $(document).ready(function () {
            for (var i = 0; i < 40; i++) {
                if ($("#InUse_" + i).val() == 'True') {
                    $('#itemblock_' + i).removeClass('hidden');
                }
            }
        });

        //function RemoveJurPrice(item) {
        //    $("#InUse_" + item).val(false);
        //    $('#itemblock_' + item).addClass('hidden');
        //}

      //function AddJurPrice(item) {
      //  console.log('jusris price js');
      //      console.log(item);
      //      console.log(globalLastIndex);
      //      if (globalLastIndex == 0) {
      //          globalLastIndex = item + 1;
      //          $("#InUse_" + globalLastIndex).val(true);
      //          $('#itemblock_' + globalLastIndex).removeClass('hidden');
      //      }
      //      else {
      //          globalLastIndex++;
      //          $("#InUse_" + globalLastIndex).val(true);
      //          $('#itemblock_' + globalLastIndex).removeClass('hidden');
      //      }

      //  }

    </script>

}

WLA3/WLA3/Views/WLA/ClientPreferences.cshtml
@model WLA3.ViewModels.Master_ViewModel.MVM

@{
    ViewBag.Title = "ClientPreferences";
}
@Html.ActionLink("Home", "GetIdentifierList", "WLA")
<hr />

<div class="customPanel">
    <div class="panel-group" id="accordion_JurisdictionInfo" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="JIHeader">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#JIHeader" href="#collapseJI" aria-expanded="true" aria-controls="collapseJI">
                        <span style="font-size: 1.3em;">Client Jurisdiction Information</span>
                    </a>
                </h4>
            </div>
            <div id="collapseJI" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="collapseJI">
                <div class="panel-body">
                    <p>Click on the column headers to sort</p>
                    <div class="table-responsive">
                        <table id="InfoTable" class="tablesorter table">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Jurisdiction Id</th>
                                    <th>Client Id</th>
                                    <th>Jurisdiction Title</th>
                                    <th>Zipcodes</th>
                                    <th>Out of Area</th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.WLAVMMaster.CM_ILL)
                                {
                                    <tr>
                                        <td>
                                            @if (item.OutOfArea == true)
                                            {
                                                @Html.ActionLink("Edit", "EditOutOfAreaJurisdiction", new { ClientId = item.ClientId, ActionType = "Edit", JurisdictionId = item.JurisdictionId }, new { @class = "btn btn-primary ", @role = "button" })
                                            }
                                            else
                                            {
                                                @Html.ActionLink("Edit", "EditIdentifierList", new { ClientId = item.ClientId, ActionType = "Edit", JurisdictionId = item.JurisdictionId }, new { @class = "btn btn-primary ", @role = "button" })
                                            }

                                        </td>
                                        <td>@item.JurisdictionId</td>
                                        <td>@item.ClientId</td>
                                        <td class="jName">@item.JurisdictionName</td>
                                        <td>@item.JurisdictionZipcodes</td>
                                        <td>@item.OutOfArea</td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                        @if (Model.WLAVMMaster.CM_ILL.Any(c => c.ClientId.ToUpper() == "DEFAULT"))
                        {

                        }
                        else
                        {
                            @Html.ActionLink("Add New Jurisdiction From Template", "AddJurisdiction", new { ClientId = Model.WLAVMMaster.CM_ILL.Select(c => c.ClientId).ToList().LastOrDefault(), ActionType = "Temp", JurisdictionId = Model.WLAVMMaster.CM_ILL.Where(c => c.JurisdictionId != 0).Select(c => c.JurisdictionId).ToList().FirstOrDefault() }, new { @class = "btn btn-primary ", @style = "margin-right: 10px;", @role = "button" })
                            @Html.ActionLink("Add New Blank Jurisdiction", "AddJurisdiction", new { ClientId = Model.WLAVMMaster.CM_ILL.Select(c => c.ClientId).ToList().LastOrDefault(), ActionType = "New", JurisdictionId = Model.WLAVMMaster.CM_ILL.Select(c => c.JurisdictionId).ToList().LastOrDefault() }, new { @class = "btn btn-primary ", @role = "button" })
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="customPanel">
    <div class="panel-group" id="accordion_JurisdictionQuickInfo" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="JQIHeader">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#JQIHeader" href="#collapseJQI" aria-expanded="true" aria-controls="collapseJQI">
                        <span style="font-size: 1.3em;">Quick Jurisdiction Price Information</span>
                    </a>
                </h4>
            </div>
            <div id="collapseJQI" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="collapseJQI">
                <div class="panel-body">
                    <p>Click on the column headers to sort</p>
                    <div class="table-responsive">
                        @{Html.RenderPartial("_JurisdictionInfo", Model.WLAVMMaster.JInfo);}
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="customPanel">
    <div class="panel-group" id="accordion_LockboxInfo" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="LockboxHeader">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#LockboxHeader" href="#collapseLockbox" aria-expanded="true" aria-controls="collapseLockbox">
                        <span style="font-size: 1.3em;">Lockbox Information</span>
                    </a>
                </h4>
            </div>
            <div id="collapseLockbox" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="collapseLockbox">
                <div class="panel-body">
                    <p>Click on the column headers to sort</p>
                    <div class="table-responsive">
                        @{Html.RenderPartial("_LockboxInfo", Model.WLAVMMaster.LBInfo);}
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div id="waiting-outter" class="hidden">
    <div id="waiting-inner">
        <img src="https://licensepet.com/wl3/rc/Content/Images/catLoaderNoBG.gif" class="waiting-img" alt="Loading Cat" />
    </div>
</div>


@section Scripts{
    <script type="text/javascript">


		$(document).ready(function () {
			$('#waiting-outter').addClass('hidden');
		});

		function editIdentifier(webclientid, identifierid, jurisdictionId, clientId) {
			console.log(webclientid);
			console.log(identifierid);
			console.log(jurisdictionId);
			console.log(clientId);


	@*var data = {
		webClientId: webclientid,
		identifierId: identifierid,
		clientId: clientId,
		jurisdictionId: jurisdictionId
	};

			$('body, html').scrollTop($('#'+ element.id).offset().top - 15);

			$.ajax({
				url: "@Url.Action("EditIndividualIdentifier", "Home")",
				type: 'POST',
			dataType: 'html',
			data: data,
			success: function (data) {
				$('#EditIdentifier').html(data);
				$('#EditIdentifier').removeClass('hidden');
			},
			error: function (data) {

			}
		});*@
		}

    </script>


}

WLA3/WLA3/Views/WLA/EditOutOfAreaJurisdiction.cshtml
@{
    ViewBag.Title = "Edit Out Of Area Jurisdiction";
}

<h2>Edit Out Of Area Jurisdiction</h2>

WLA3/WLA3/Views/WLA/Index.cshtml
@{
	ViewBag.Title = "Start Page";
}


<div id="JurisdictionInformationList"></div>
<div id="IdentifierList"></div>
<div id="EditIdentifier"></div>

WLA3/WLA3/Views/WLA/UpdateJurisdictionPrice.cshtml
@model WLA3.ViewModels.Master_ViewModel.MVM

@{
    ViewBag.Title = "Add Jurisdiction";
}
@Html.ActionLink("Home", "GetIdentifierList", "WLA")
<hr />
<h2>Edit Jurisdiction</h2>

<p>Client Id: @Model.WLAVMMaster.JConfig.ClientId</p>

@using (Html.BeginForm("EditJurisdictionPrice", "WLA", FormMethod.Post, new { id = "JPriceUpdate" }))
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_JurisdictionPrice", Model);


    <div class="clearfix"></div>
    <div class="form-group" style="margin-top: 10px;">
        <input type="submit" value="Save" class="btn btn-success" style="width: 75%; display: block; margin: 0 auto;" />

    </div>

}