WLA3/WLA3/ViewModels/ImageApproval_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WLA3.Models;

namespace WLA3.ViewModels
{
	public class ImageApproval_ViewModel
	{
		public List<ImageInformation> ImageList { get; set; }
		public UtilityModel DUM { get; set; }
		public int? TotalAnimalCount { get; set; }
	}
}

WLA3/WLA3/Controllers/ImageApprovalController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WLA3.Models;
using WLA3.ViewModels;

namespace WLA3.Controllers
{
	public class ImageApprovalController : Controller
	{

		DatabaseController dbC = new DatabaseController();
		UtilityController uc = new UtilityController();


		public ActionResult GetPendingImages()
		{
			var master = new Master_ViewModel.MVM();
			master.CLM = new CustomModels.ClientLookupModel();
			master.CLM.User = Session["User"].ToString();
			master.CLM.Password = Session["Password"].ToString();
			master.CLM.ClientId = "HLP";

			if (master.CLM == null || (master.CLM.User == null || master.CLM.Password == null || master.CLM.ClientId == null))
			{
				if (master.CLM == null)
					master.CLM = new CustomModels.ClientLookupModel();
				var unpw = dbC.GetUNPW();
				master.CLM.User = unpw.User;
				master.CLM.Password = unpw.Password;
				master.CLM.ClientId = unpw.ClientId;
			}

			dbC.SetUNPW("Animal", master.CLM.User, master.CLM.Password, master.CLM.ClientId);

			master.ImageApprovalMaster = new ImageApproval_ViewModel();
			master.ImageApprovalMaster.ImageList = new List<ImageInformation>(dbC.getPendingImages());

			foreach(var item in master.ImageApprovalMaster.ImageList)
      {
				var breedReqId = item.BreedRequestInfo.BreedRequestId;
				var patronEmail = item.PersonInfo.EmailAddress;
				item.BreedRequestInfo.EditHash = GetMD5Hash(breedReqId, patronEmail);
			}

			var DUM = new UtilityModel
			{
				animalType = uc.GetAnimalType(),
				stateList = uc.GetStates(),
				sexList = uc.GetAnimalSex(),
				requestFormat = uc.GetRequestFormat(),
				ageList = uc.GetAgeList(),
				breedInfo = uc.getBreedInfo(),
				requestStatus = uc.GetStatusList(),
				sizeList = uc.GetSizeList(),
				requestType = uc.GetInterestTypeList(),
				colorList = uc.GetColorList(),
				coatList = uc.GetCoatList(),
				tailList = uc.GetTailList(),
				earList = uc.GetEarList(),
				noseList = uc.GetNoseList(),
				collarType = uc.GetCollarTypeList(),
				collarColor = uc.GetCollarColorList()
			};
			master.ImageApprovalMaster.DUM = DUM;

			master.ImageApprovalMaster.TotalAnimalCount = dbC.getImageCount();

			return View(master);
		}

		[HttpPost]
		public ActionResult MassApproveImages(Master_ViewModel.MVM mVM) {
			ApproveItems(mVM.ImageApprovalMaster.ImageList);
			//dbC.approveAllImages(mVM.ImageApprovalMaster.ImageList);
			//dbC.updateBreedRequestInformation(mVM.ImageApprovalMaster.ImageList.Where(update => update.FormChanged == true).ToList());
			return GetDisapprovedImages(mVM);
		}

		[HttpPost]
		public ActionResult GetSpecificRequest(string ImageLookup)
		{
			var master = new Master_ViewModel.MVM();

			master.ImageApprovalMaster = new ImageApproval_ViewModel();
			master.ImageApprovalMaster.ImageList = dbC.lookupBy(ImageLookup);
			if (!String.IsNullOrWhiteSpace(ImageLookup))
			{
				master.ImageApprovalMaster.ImageList = dbC.lookupBy(ImageLookup);
			}

			foreach (var item in master.ImageApprovalMaster.ImageList)
			{
				var breedReqId = item.BreedRequestInfo.BreedRequestId;
				var patronEmail = item.PersonInfo.EmailAddress;
				item.BreedRequestInfo.EditHash = GetMD5Hash(breedReqId, patronEmail);
			}

			var DUM = new UtilityModel
			{
				animalType = uc.GetAnimalType(),
				stateList = uc.GetStates(),
				sexList = uc.GetAnimalSex(),
				requestFormat = uc.GetRequestFormat(),
				ageList = uc.GetAgeList(),
				breedInfo = uc.getBreedInfo(),
				requestStatus = uc.GetStatusList(),
				sizeList = uc.GetSizeList(),
				requestType = uc.GetInterestTypeList(),
				colorList = uc.GetColorList(),
				coatList = uc.GetCoatList(),
				tailList = uc.GetTailList(),
				earList = uc.GetEarList(),
				noseList = uc.GetNoseList(),
				collarType = uc.GetCollarTypeList(),
				collarColor = uc.GetCollarColorList()
			};
			master.ImageApprovalMaster.DUM = DUM;

			master.ImageApprovalMaster.TotalAnimalCount = 1;

			return View("GetSpecificRequest", master);
		}

		[HttpGet]
		public ActionResult GetDisapprovedImages(Master_ViewModel.MVM mVM)
		{
			var disapprovedImages = new List<ImageInformation>();

			foreach(var request in mVM.ImageApprovalMaster.ImageList)
			{
				if(request.Approved == false)
				{
					disapprovedImages.Add(dbC.getIndividualImageByID(request.ImageId, request.ImageSequence));
				}
			}

			mVM.ImageApprovalMaster.ImageList = disapprovedImages;

			return View("GetDisapprovedImages", mVM);
		}


		[HttpPost]
		public ActionResult SaveIndividualItem([Bind(Prefix = "item")] ImageInformation imageContents)
		{
			if(imageContents.ImageNew == true)
			{
				imageContents.ImageSequence += 1;
			}

			var imageList = new List<ImageInformation>();
			imageList.Add(imageContents);
			ApproveItems(imageList);

			return RedirectToAction("GetPendingImages");
		}


		internal void ApproveItems(List<ImageInformation> imageList)
		{
			dbC.approveAllImages(imageList);
			dbC.updateBreedRequestInformation(imageList.Where(update => update.FormChanged == true).ToList());
		}

		internal string GetMD5Hash(string breedReqId, string emailAddress)
		{
			var hashString = breedReqId + emailAddress;
			var verificationHash = MD5(hashString);
			return verificationHash.Substring(3, 8);
		}

		internal string MD5(string source)
		{
			using (var md5Service = new MD5CryptoServiceProvider())
			{
				var bytes = md5Service.ComputeHash(Encoding.ASCII.GetBytes(source));
				var hash = "";
				var builder = new StringBuilder();
				builder.Append(hash);
				foreach (byte ByteVal in bytes)
				{
					builder.Append(ByteVal.ToString("x2"));
				}
				hash = builder.ToString();
				return hash;
			}
		}
	}
}

WLA3/WLA3/Views/ImageApproval/GetDisapprovedImages.cshtml
@model WLA3.ViewModels.Master_ViewModel.MVM

@{
	ViewBag.Title = "Disapproved Images";
	var lastIndex = 0;
}

<h2>Disapproved Images</h2>
<hr />

@using (Html.BeginForm("MassDisapproveImages", "ImageApproval", FormMethod.Post, new { id = "DisapproveImageForm" }))
{
	@Html.AntiForgeryToken()
	foreach (var item in Model.ImageApprovalMaster.ImageList)
	{

		<div class="pictureBlock" id="@item.ImageId">
			<div id="overlay_@item.ImageId">
				<div id="undo_unapprove_@item.ImageId" class="undoUnapprove hidden" onclick="undoDisapprove('@item.ImageId')">Undo</div>
			</div>
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].Approved, new { id = "disapproved_" + item.ImageId })
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].ImageId)
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].ImageSequence)
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].UserId)
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].ImageResolution)
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].PersonInfo.EmailAddress)
			@Html.HiddenFor(model => Model.ImageApprovalMaster.ImageList[lastIndex].BreedRequestInfo.ProperName)
			<img src="@item.ImageData" class="my_popup_open" onclick="largerImage('@item.ImageData');" />
			<br />@item.ImageId / @item.ImageSequence
			<br /><b>@item.BreedRequestInfo.ProperName</b>
			<br />@item.BreedRequestInfo.RequestStatus
			<br />@item.BreedRequestInfo.InterestType
			<br />@item.PersonInfo.EmailAddress
			<div class="clearfix"></div>
			<hr />
			<div id="DisapproveOptions_@item.ImageId">

			</div>

		</div>
		lastIndex = lastIndex + 1;
	}
	<div class="clearfix"></div>
	<div class="itemBlock" style="margin-top: 30px;">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Save disapprovals and go back to pending images" class="btn btn-default subBtn" />
		</div>
	</div>
}
<div class="clearfix"></div>

<div id="donationDescriptionBox" class="hidden">
	<div id="imagePopupBox" @*class="hidden"*@>
		<div class="imageBox">
			<canvas id="animalCanvas" style="width: 100%; height: 500px;"></canvas>
			<div id="largeImageInBox"></div>
			<div id="imgBtnBox">
				@*<button class="imagePopupBox_close">Close</button>*@
				<button class="btn btn-default " value="Close" onclick="$('#donationDescriptionBox').addClass('hidden')">Close</button>
			</div>
		</div>
	</div>
</div>

WLA3/WLA3/Views/ImageApproval/_EditForm.cshtml
@model WLA3.Models.ImageInformation

<h2>Person Info</h2>
<hr/>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.FirstName)
	@Html.TextBoxFor(model => model.PersonInfo.FirstName, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.LastName)
	@Html.TextBoxFor(model => model.PersonInfo.LastName, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.Label("Phone Number")
	@Html.TextBoxFor(model => model.PersonInfo.AreaCode, new { @class = "form-control" })
	@Html.TextBoxFor(model => model.PersonInfo.PhoneNumber, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.Address)
	@Html.TextBoxFor(model => model.PersonInfo.Address, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.City)
	@Html.TextBoxFor(model => model.PersonInfo.City, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.State)
	@Html.DropDownListFor(model => model.PersonInfo.State, new SelectList(Model.utilityModel.stateList, "stateKey", "stateText", Model.PersonInfo.State), new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.ZipCode)
	@Html.TextBoxFor(model => model.PersonInfo.ZipCode, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.EmailFormat)
	@Html.DropDownListFor(model => model.PersonInfo.EmailFormat, new List<SelectListItem> { new SelectListItem() { Text = "Please Select", Value = "" } }, new { @class = "form-control" })
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.PersonInfo.EmailAddress): &nbsp;
	@Html.DisplayFor(model => model.PersonInfo.EmailAddress)
</div>
<hr/>
<h2>Animal Info</h2>
<hr/>
<div class="itemBlock">
	@Html.LabelFor(model => model.BreedRequestInfo.BreedRequestId): &nbsp;
	@Html.DisplayFor(model => model.BreedRequestInfo.BreedRequestId)
</div>
<div class="itemBlock">
	@Html.LabelFor(model => model.BreedRequestInfo.RequestStatus)
	@Html.TextBoxFor(model => model.BreedRequestInfo.RequestStatus, new { @class = "form-control" })
</div>